spring:
    application:
        name: product-service
    cloud:
        function:
            definition: consumeOrderCreatedEvent
        stream:
            bindings:
                testEvent-out-0:
                    destination: test-topic
                    content-type: application/json
                consumeOrderCreatedEvent-in-0:
                    destination: order-created-topic
                    group: product-service-group
            kafka:
                binder:
                    brokers: localhost:9092
    datasource:
        url: jdbc:postgresql://localhost:5433/products
        username: postgres
        password: test12345
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
server:
    port: 8083